[package]
name = "bevy_common_systems"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_enhanced_input = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true

[features]
debug = []
