[package]
name = "bevy_common_systems_macros"
version = "0.0.1"
edition = "2021"
description = "Procedural macros for Bevy common systems"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro2 = "1"
